### ISSUE TITLE
Only the creator can access a compute instance Error

### ISSUE THREAD

**Issue by nish112** [MicrosoftLearning/DP100#20]
Hi, 

I am currently using Azure pass subscription and currently working on DP-100 labs. I got the "Only the creator can access a compute instance" error when i clicked the Jupyter link from the compute instance i created. 

1. I am using, my personal Outlook Account
2. I have assigned the Role Owner as mentioned in the lab instruction
3. I deleted the history and everything, login again but same issue persists
4. I tried and restarting the compute, created a new compute instance but same issue persisted.

Please help!!
![github](https://user-images.githubusercontent.com/26849166/80568048-e3dacb00-8a13-11ea-9227-38671250afa7.jpg)

**Comment by RuggieroLauria** [comment]
I'm Owner and I get:
WARNING - Failed to authenticate '{'additional_properties': {}, 'id': '/tenants/b16130f0-1d1b-4d9d-97cd-24b3905b6d09', 'tenant_id': 'b16130f0-1d1b-4d9d-97cd-24b3905b6d09'}' due to error 'Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\r\nTrace ID: c28eb7f0-cb29-49ac-b3fa-ecc16e768600\r\nCorrelation ID: 2303beb8-0ee4-4524-8c29-00203738c330\r\nTimestamp: 2020-05-01 18:22:19Z","error_codes":[50076],"timestamp":"2020-05-01 18:22:19Z","trace_id":"c28eb7f0-cb29-49ac-b3fa-ecc16e768600","correlation_id":"2303beb8-0ee4-4524-8c29-00203738c330","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}'

**Comment by RuggieroLauria** [comment]
Half classroom blocked due of this problem.
One week delay for the response
Please answer

**Comment by dnt91** [comment]
Hi, Same issue, I used the azure notebooks instead (https://notebook.azure.com) and change the compute target to aml-cluster

**Comment by RuggieroLauria** [comment]
> Hi, Same issue, I used the azure notebooks instead (https://notebook.azure.com) and change the compute target to aml-cluster

https://notebooks.azure.com not https://notebook.azure.com
And please can you specify which paramaters have you used?

**Comment by dnt91** [comment]
> > Hi, Same issue, I used the azure notebooks instead (https://notebook.azure.com) and change the compute target to aml-cluster
> 
> https://notebooks.azure.com not https://notebook.azure.com
> And please can you specify which paramaters have you used?

Yes You're right! I didn't care about the url :(
But I don't understand which parameters ?
Using Azure notebooks I just logged myselft and download the github files as a new notebook project.

**Comment by GraemeMalcolm** [comment]
The most likely cause is cached credentials or a firewall issue.
Try using an InPrivate browser tab, and if that doesn't work try using the embedded Notebooks in Azure ML Studio instead Jupyter.

**Comment by dnt91** [comment]
I tested in private browsing and it didn't necessarily work better. In fact after several attempts (6 for me, 3 for some students) it worked ... but sometimes it also stopped working for no apparent reason. The firewall is not at fault either and there were at least 10 of us connecting from different locations each time. The only way to get a reliable service was through Azure notebooks.
